// orchestrator/index.ts — Barrel re-export for the orchestrator module
export type {
    PlanTask,
    SpecResponse,
    PlanResponse,
    PlanOutlineResponse,
    OperationResponse,
    SummaryResponse,
    QaAcceptanceItem,
    QaResponse,
    ExecutionInput,
    TaskContextPack,
    ModelTrace,
    OperationResult,
    QaResult,
    RunDiagnostics,
    CompletionMode,
    ArchitectPlanResponse,
    FileContract,
    ImportContract,
    ExportContract,
    DbQueryContract,
    SkeletonDagNode,
    SkeletonSpecDagResponse,
    FixDagTask,
    FixDagResponse,
    StructureLock,
    SkeletonFile,
} from "./types";

export {
    SPEC_SCHEMA,
    PLAN_SCHEMA,
    PLAN_OUTLINE_SCHEMA,
    OPERATIONS_SCHEMA,
    SUMMARY_SCHEMA,
    QA_SCHEMA,
    ARCHITECT_PLAN_SCHEMA,
    SKELETON_SPEC_DAG_SCHEMA,
    SKELETON_FILL_SCHEMA,
    SKELETON_AUTOFIX_SCHEMA,
    FIX_DAG_SCHEMA,
} from "./schemas";

export {
    MAX_PLAN_TASKS,
    CONTEXT_FILE_LIMIT,
    CONTEXT_CHAR_BUDGET,
    MAX_USER_ERROR_LENGTH,
    ACCEPTANCE_GATE_MIN_SCORE,
    ACCEPTANCE_HARD_FAIL_SCORE,
    BASE_AGENT_SYSTEM_PROMPT,
    STARTER_TEMPLATE_FILES,
} from "./prompts";

export {
    assertNonTerminal,
    toSafeJson,
    compactErrorMessage,
    toUserFacingAgentError,
    getThreadPromptContext,
    buildThreadPromptContextPack,
    toModelTrace,
    buildFileCatalog,
    createWorkingTreeDigest,
    buildRepoMapSummary,
    buildTaskContextPack,
    computeFileSet,
    summarizeTreeChanges,
    formatSpecForPrompt,
    getPriorRunContext,
    runSnapshotFiles,
    ensureRunExists,
    updateRunAndReload,
    pruneNoOpOperations,
    countOperationKinds,
    initializeDiagnostics,
    estimateSpecQualityScore,
    persistRunMemoryCards,
} from "./context";

export {
    normalizeSpecResponse,
    normalizePlanResponse,
    normalizePlanOutlineResponse,
    normalizeOperationResponse,
    normalizeQaResponse,
    normalizeSkeletonSpecDagResponse,
    normalizeFixDagResponse,
} from "./normalizers";

export {
    generateSpec,
    generatePlanOutline,
    generateSkeletonSpecDag,
    generateSkeletonFile,
    generateSkeletonAutofix,
    generateFillForSkeleton,
    generateFixDag,
    generateFixOperations,
    generateQaVerdict,
    generateFinalSummary,
} from "./generators";
